apiVersion: batch/v1
kind: Job
metadata:
  name: demo-data-generator
  namespace: ez-platform
  labels:
    app: demo-data-generator
    component: tools
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: demo-data-generator
    spec:
      restartPolicy: Never
      containers:
      - name: demo-data-generator
        image: ez-platform/demo-data-generator:latest
        imagePullPolicy: Never
        args:
          - "--mongodb-connection=mongodb"
        env:
          - name: DOTNET_ENVIRONMENT
            value: "Production"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
